import streamlit as st
import onnxruntime as ort
import numpy as np
import pandas as pd


# =========================================
# Load ONNX Ocean AI Model
# =========================================

session = ort.InferenceSession(
    "models/real_ocean_model.onnx"
)

input_name = session.get_inputs()[0].name


# =========================================
# Streamlit page
# =========================================

st.set_page_config(
    page_title="Ocean Deep Temperature Predictor",
    page_icon="🌊",
    layout="wide"
)

st.title(
    "🌊 Ocean Deep Temperature Predictor"
)

st.write(
    "Predict ocean temperature at different "
    "depths using real satellite SST and "
    "surface salinity."
)

st.divider()


# =========================================
# Inputs
# =========================================

st.subheader(
    "🌍 Ocean Location and Surface Data"
)

col1, col2 = st.columns(2)

with col1:

    latitude = st.number_input(
        "Latitude",
        min_value=-90.0,
        max_value=90.0,
        value=10.0
    )

    longitude = st.number_input(
        "Longitude",
        min_value=-180.0,
        max_value=180.0,
        value=70.0
    )

with col2:

    sst = st.number_input(
        "Surface Temperature / SST (°C)",
        value=28.5
    )

    sss = st.number_input(
        "Surface Salinity / SSS",
        value=35.2
    )


st.info(
    f"📍 Location: "
    f"{latitude:.2f}°, {longitude:.2f}°"
)

st.divider()


# =========================================
# Prediction
# =========================================

if st.button(
    "🔮 Predict Ocean Temperature",
    type="primary"
):

    results = []

    for depth in range(
        50,
        1001,
        50
    ):

        input_data = np.array(
            [[
                latitude,
                longitude,
                sst,
                sss,
                float(depth)
            ]],
            dtype=np.float32
        )

        prediction = session.run(
            None,
            {
                input_name: input_data
            }
        )

        temperature = float(
            prediction[0][0][0]
        )

        results.append(
            (
                depth,
                temperature
            )
        )


    # =====================================
    # Results
    # =====================================

    st.subheader(
        "🌊 Predicted Ocean Temperature"
    )

    st.caption(
        "Predictions are generated by the "
        "real-data trained model."
    )


    chart_data = pd.DataFrame(
        results,
        columns=[
            "Depth (m)",
            "Temperature (°C)"
        ]
    )


    st.line_chart(
        chart_data,
        x="Depth (m)",
        y="Temperature (°C)"
    )


    st.subheader(
        "📊 Depth Profile"
    )

    st.dataframe(
        chart_data,
        use_container_width=True,
        hide_index=True
    )